# -*- coding: utf-8 -*-
"""TEXT cleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJGuM1vGsuJJAnGFlpssHzqcHaycThHY
"""

#load the dataset
import pandas as pd
dataset=pd.read_csv('tweets.csv',encoding='ISO-8859-1')

dataset.head()

dataset.tail()

import re

def clean_text(text):
  #remove RT
  text=re.sub(r'RT','',text)
 #Fix &
  text=re.sub(r'&amp:','',text)
  #remove punctuations
  text=re.sub(r'[?!.;:,#@-]','',text)

  text=text.lower()
  return text

!pip install wordcloud

#import list of stopwards
from wordcloud import STOPWORDS
print(STOPWORDS)

dataset.text=dataset.text.apply(lambda x: clean_text(x))

dataset.head()

